name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Build the app
        run: sudo su && cd "botnet apk" && chmod +x gradlew && bash ./gradlew assembleDebug --stacktrace
        
      - name: WHERE AM I
        run:  cd .. && cd "botnet apk" && ls
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/
          #path: app/build/outputs/apk/debug/app-debug.apk
